### ISSUE TITLE
json output in rate fields

### ISSUE THREAD

**Issue by daveofthedogs** [Seventh-State/rabbitmq-monitoring#3] opened 2024-07-31 16:35 UTC
I am seeing json output in the rate fields for the Queues Overview.  Does an aggregator need to be added?
RMQ 3.13.1
Grafana:  11.1.0

<img width="1692" alt="image" src="https://github.com/user-attachments/assets/569c8e5d-a401-4cf9-8221-2ca8c751af07">

Publish rate example:
```
{
  "fields": [
    {
      "name": "Time",
      "type": "time",
      "typeInfo": {
        "frame": "time.Time"
      },
      "config": {
        "interval": 15000
      },
      "values": [
        1722443415000,
        1722443430000,
        1722443445000,
        1722443460000,
        1722443475000,
        1722443490000,
        1722443505000,
        1722443520000,
        1722443535000,
        1722443550000,
        1722443565000,
        1722443580000,
        1722443595000,
        1722443610000,
        1722443625000,
        1722443640000,
        1722443655000,
        1722443670000,
        1722443685000,
        1722443700000,
        1722443715000
      ],
      "entities": {},
      "state": null
    },
    {
      "name": "Value",
      "type": "number",
      "typeInfo": {
        "frame": "float64"
      },
      "labels": {
        "queue": "TICKETING.ENTITLEMENT.KEYRINGMAIN.AUDQ",
        "rabbitmq_cluster": "latest.dlr-ent-rmq-a.wdprapps.disney.com"
      },
      "config": {},
      "values": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0.20001333422228146,
        0.2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "entities": {},
      "state": {
        "calcs": {
          "lastNotNull": 0
        }
      }
    }
  ],
  "first": [
    1722443415000,
    1722443430000,
    1722443445000,
    1722443460000,
    1722443475000,
    1722443490000,
    1722443505000,
    1722443520000,
    1722443535000,
    1722443550000,
    1722443565000,
    1722443580000,
    1722443595000,
    1722443610000,
    1722443625000,
    1722443640000,
    1722443655000,
    1722443670000,
    1722443685000,
    1722443700000,
    1722443715000
  ],
  "length": 21,
  "value": 0
}
```

**Comment by anhanhnguyen** [comment] 2024-11-27 08:42
Hi @daveofthedogs,

We've updated the dashboard to address the issue. It appears the problem was caused by Grafana's transformation when handling missing data. We've implemented a workaround with the metric query.

Please try it out and let us know if you encounter any further issues.

**Comment by luos** [comment] 2024-12-10 16:30
Thank you for reporting, this is now fixed. 🙂 
Dashboards are updated on Grafana as well. 

Let us know if it does not work. 🙂

**Closed by luos** 2024-12-10 16:30 UTC
